management:
  endpoints.web.exposure.include: health,info,metrics,gateway
  endpoint.health.show-details: always
  endpoint.gateway.access: read-only
  prometheus.metrics.export.enabled: true
  info.env.enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: 8080
  shutdown: graceful

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user_service_base
              uri: lb://user-service
              predicates:
                - Path=/admin/users
            - id: user_service_userid
              uri: lb://user-service
              predicates:
                - Path=/admin/users/{userid}

            - id: main-service
              uri: lb://main-service
              predicates:
                - Path=/**
