management:
  endpoints.web.exposure.include: health,info,metrics,gateway
  endpoint.health.show-details: always
  endpoint.gateway.access: read-only
  prometheus.metrics.export.enabled: true
  info.env.enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: 8080
  shutdown: graceful

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user_service
              uri: lb://user-service
              predicates:
                - Path=
                    /admin/users,
                    /admin/users/*,
                    /admin/users/*/short,
                    /admin/users/all/*

            - id: comment_service
              uri: lb://comment-service
              predicates:
                - Path=
                    /comments/**, 
                    /events/*/comments/**, 
                    /users/*/events/*/comments, 
                    /users/*/comments/**, 
                    /admin/comments/**, 
                    /admin/users/*/comments

            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/**
